"""
Django settings for Test_Database_4 project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path
import sys
import atexit
from pymongo import MongoClient

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i=@y9x%wolaj27qc07w(rnv463*)kqjq_u8k3_*l7l6havv4+&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sensor_4_app',
    'rest_framework',
    'process_encoder',
    'experiments',
    'corsheaders',
    'batch_encoder',
    'channels',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True


CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Content-Disposition',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',  # Add OPTIONS to the allowed methods
    'PATCH',
    'POST',
    'PUT',
]

ROOT_URLCONF = 'Test_Database_4.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#WSGI_APPLICATION = 'Test_Database_4.wsgi.application'

ASGI_APPLICATION = 'Test_Database_4.asgi.application'

# Channels layer using Redis
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get("REDIS_URL", "redis://redis:6379/0")],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


IS_TESTING = 'test' in sys.argv or 'pytest' in sys.argv[0]

# Parse MongoDB URI properly for Docker
MONGODB_URI = os.environ.get('MONGODB_URI', 'mongodb://localhost:27017')
# Extract database name from URI or use default
if '/LocalTest' in MONGODB_URI:
    MONGODB_HOST = MONGODB_URI
    MONGODB_DB_NAME = 'LocalTest'
else:
    MONGODB_HOST = MONGODB_URI + '/LocalTest'
    MONGODB_DB_NAME = 'LocalTest'

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': MONGODB_DB_NAME,
        'CLIENT': {
            'host': MONGODB_HOST,
            'name': 'TestDB' if IS_TESTING else MONGODB_DB_NAME
        }
    }
}

if IS_TESTING:
    print("🧪 Running tests on isolated MongoDB database: TestDB")

    def cleanup_test_db():
        print("🧹 Dropping TestDB after test run...")
        client = MongoClient('mongodb://localhost:27017')
        client.drop_database('TestDB')

    atexit.register(cleanup_test_db)


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


CELERY_BROKER_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("REDIS_URL", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

# Store results in Redis instead of database
CELERY_CACHE_BACKEND = 'redis//localhost:6379/1'
CELERY_RESULTS_EXPIRES = 3600
