# Generated by Django 3.2 on 2025-08-12 04:17

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessFile',
            fields=[
                ('process_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('scope', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.FileField(upload_to='uploads/')),
                ('parsed_data', djongo.models.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('process_id', models.CharField(max_length=10, unique=True)),
                ('scope', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.FileField(upload_to='uploads/')),
                ('parsed_data', djongo.models.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
