# Generated by Django 3.2.25 on 2025-09-09 06:02

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(upload_to='sensor-images/')),
                ('original_file', models.ImageField(null=True, upload_to='sensor-images/tiffs')),
                ('sensor_unique_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('upload_date', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'batch_encoder_image',
            },
        ),
        migrations.CreateModel(
            name='ImageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_unique_id', models.CharField(db_index=True, max_length=20)),
                ('process_id', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('group_key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('images_data', djongo.models.fields.JSONField(default=list)),
                ('image_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('batch_location', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('batch_id', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'batch_encoder_image_group',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_location', models.CharField(db_index=True, max_length=5)),
                ('batch_id', models.IntegerField(db_index=True)),
                ('total_wafers', models.IntegerField()),
                ('batch_label', models.CharField(blank=True, max_length=225, null=True)),
                ('batch_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('wafer_id', models.IntegerField(db_index=True)),
                ('wafer_label', models.CharField(blank=True, max_length=225, null=True)),
                ('total_sensors', models.IntegerField()),
                ('wafer_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('wafer_design_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sensor_id', models.IntegerField(db_index=True)),
                ('sensor_label', models.CharField(blank=True, max_length=10, null=True)),
                ('sensor_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('processes', djongo.models.fields.JSONField(blank=True, default=list)),
                ('process_ids', djongo.models.fields.JSONField(blank=True, default=list)),
                ('last_process_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('process_count', models.IntegerField(db_index=True, default=0)),
                ('unique_identifier', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'batch_encoder_sensor',
            },
        ),
        migrations.CreateModel(
            name='SensorLabel',
            fields=[
                ('name', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['batch_location', 'batch_id'], name='batch_encod_batch_l_0b84c3_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['wafer_id', 'sensor_id'], name='batch_encod_wafer_i_30903c_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['batch_location', 'process_count'], name='batch_encod_batch_l_2d5a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['unique_identifier', 'process_count'], name='batch_encod_unique__c2482a_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegroup',
            index=models.Index(fields=['sensor_unique_id', 'process_id'], name='batch_encod_sensor__e8858d_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegroup',
            index=models.Index(fields=['batch_location', 'batch_id'], name='batch_encod_batch_l_97120c_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegroup',
            index=models.Index(fields=['image_count'], name='batch_encod_image_c_a502f7_idx'),
        ),
        migrations.AddField(
            model_name='image',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='batch_encoder.sensor'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['sensor_unique_id', 'process_id'], name='batch_encod_sensor__e03c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['process_id', 'upload_date'], name='batch_encod_process_088184_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['sensor', 'process_id'], name='batch_encod_sensor__7c6f64_idx'),
        ),
    ]
