# Generated by Django 3.2 on 2025-02-11 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process_encoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_location', models.CharField(db_index=True, max_length=5)),
                ('batch_id', models.IntegerField(db_index=True)),
                ('total_wafers', models.IntegerField()),
                ('batch_label', models.CharField(blank=True, max_length=225, null=True)),
                ('batch_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('wafer_id', models.IntegerField(db_index=True)),
                ('wafer_label', models.CharField(blank=True, max_length=225, null=True)),
                ('total_sensors', models.IntegerField()),
                ('wafer_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('wafer_design_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sensor_id', models.IntegerField(db_index=True)),
                ('sensor_label', models.CharField(blank=True, max_length=225, null=True)),
                ('sensor_description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorProcessRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('unique_identifier', models.CharField(db_index=True, max_length=100)),
                ('process_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_encoder.processfile')),
                ('sensor', models.ForeignKey(db_column='sensor', on_delete=django.db.models.deletion.CASCADE, related_name='process_relations', to='sensor_4_app.sensor')),
            ],
            options={
                'unique_together': {('process_file', 'sensor')},
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_process_relations',
            field=models.ManyToManyField(related_name='related_processes', through='sensor_4_app.SensorProcessRelation', to='process_encoder.ProcessFile'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(upload_to='sensor-images/')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sensor_4_app.sensor')),
            ],
        ),
    ]
