# Generated by Django 3.2 on 2025-08-12 04:17

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process_encoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(upload_to='sensor-images/')),
                ('sensor_unique_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('upload_date', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'sensor_4_app_image',
            },
        ),
        migrations.CreateModel(
            name='ImageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_unique_id', models.CharField(db_index=True, max_length=20)),
                ('process_id', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('group_key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('images_data', djongo.models.fields.JSONField(default=list)),
                ('image_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'image_group',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_location', models.CharField(db_index=True, max_length=5)),
                ('batch_id', models.IntegerField(db_index=True)),
                ('total_wafers', models.IntegerField()),
                ('batch_label', models.CharField(blank=True, max_length=225, null=True)),
                ('batch_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('wafer_id', models.IntegerField(db_index=True)),
                ('wafer_label', models.CharField(blank=True, max_length=225, null=True)),
                ('total_sensors', models.IntegerField()),
                ('wafer_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('wafer_design_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sensor_id', models.IntegerField(db_index=True)),
                ('sensor_label', models.CharField(blank=True, max_length=225, null=True)),
                ('sensor_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('unique_identifier', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sensor_4_app_sensor',
            },
        ),
        migrations.CreateModel(
            name='SensorLabel',
            fields=[
                ('name', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorProcessRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('unique_identifier', models.CharField(db_index=True, max_length=100)),
                ('process_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_encoder.processfile')),
                ('sensor', models.ForeignKey(db_column='sensor', on_delete=django.db.models.deletion.CASCADE, related_name='process_relations', to='sensor_4_app.sensor')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='sensor_4_app.sensorlabel'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_process_relations',
            field=models.ManyToManyField(related_name='related_processes', through='sensor_4_app.SensorProcessRelation', to='process_encoder.ProcessFile'),
        ),
        migrations.AddIndex(
            model_name='imagegroup',
            index=models.Index(fields=['sensor_unique_id', 'process_id'], name='image_group_sensor__ed5229_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegroup',
            index=models.Index(fields=['group_key'], name='image_group_group_k_1c7c64_idx'),
        ),
        migrations.AddField(
            model_name='image',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sensor_4_app.sensor'),
        ),
        migrations.AlterUniqueTogether(
            name='sensorprocessrelation',
            unique_together={('process_file', 'sensor')},
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['unique_identifier'], name='sensor_4_ap_unique__b26d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['batch_location', 'batch_id'], name='sensor_4_ap_batch_l_e86181_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['wafer_id', 'sensor_id'], name='sensor_4_ap_wafer_i_e02f27_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['sensor_unique_id', 'process_id'], name='sensor_4_ap_sensor__b0e8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['process_id', 'upload_date'], name='sensor_4_ap_process_19e15e_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['sensor', 'process_id'], name='sensor_4_ap_sensor__16b202_idx'),
        ),
    ]
