# Generated by Django 3.2 on 2025-04-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_4_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorLabel',
            fields=[
                ('name', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='sensor_4_app.sensorlabel'),
        ),
    ]
