# Generated by Django 3.2.25 on 2025-08-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_4_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='original_file',
            field=models.ImageField(default='', upload_to='sensor-images/tiffs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagegroup',
            name='batch_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='imagegroup',
            name='batch_location',
            field=models.CharField(blank=True, db_index=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='imagegroup',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=''),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='imagegroup',
            index=models.Index(fields=['batch_location', 'batch_id'], name='image_group_batch_l_6a3a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegroup',
            index=models.Index(fields=['created_date'], name='image_group_created_c13dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegroup',
            index=models.Index(fields=['image_count'], name='image_group_image_c_d10b19_idx'),
        ),
    ]
