# Generated by Django 3.2 on 2025-04-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_4_app', '0002_auto_20250421_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='unique_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
