# Generated by Django 3.2 on 2025-04-24 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_4_app', '0004_populate_unique_identifier'),
        ('sensor_4_app', '0005_fill_in_unique_identifier'),
    ]

    operations = [
    ]
