from django.urls import path, include
from . import views

urlpatterns = [
    path('batch/',  views.bulk_create_2, name='Create Batch'),
    path('batchview/', views.bulk_electrode_view, name='View entire database'),
    path('detail/<str:batch_location>/<int:batch_id>/', views.electrodedetail, name='Details'),
    path('batches/', views.get_batches, name='View Batches'),
    path('batches/delete/<str:batch_location>/<int:batch_id>/', views.delete_batch, name='Delete Batches'),
    path('sensor/search/', views.search_electrode, name='Search function'),
    path('v2/detail/<str:batch_location>/<int:batch_id>/', views.batch_detail_2, name='Batch Detail V2'),
    path('v3/detail/<str:batch_location>/<int:batch_id>/', views.batch_detail_3, name='Batch Detail V3'),
    path('v4/detail/<str:batch_location>/<int:batch_id>/', views.batch_detail_4, name='Batch Detail V4'),
    path('electrode-dropdown/', views.electrode_dropdown, name='Electrode Dropdown'),
    path('image-upload/', views.upload_image_2, name='Image Upload'),
    path('v4/update/<str:batch_location>/<int:batch_id>/', views.update_sensors_4, name='Update Sensors'),
    path('delete_process/<str:b_l>/<int:b_id>/', views.delete_process, name='delete_process'),
    path('sensors/', views.sensors, name='Dynamic Query of Sensors'),
    path('v2/sensors/', views.sensors_2, name='Dynamic Query of Sensors 2'),
    path('v3/sensors/', views.sensors_3, name='Dynamic query 3 with process_id'),
    path('v4/sensors/', views.sensors_4, name='Sensor 4'),
    path('sensor_processes/', views.sensor_processes, name='Sensor Processes'),
    path('sp/', views.s_p, name='SP'),
    path('batches_2/', views.get_batches_2, name='Get Batches '),
    path('batches_3/', views.get_batches_3_with_processes, name='Get Batches 3'),
    path('batches_4/', views.get_batches_4, name='Batches 4'),
    path('batches_5/', views.get_batches_5, name='Batches 5'),
    path('batches_5/<str:batch_location>/<int:batch_id>/', views.get_batches_5, name='Batches 5'),
    path('batches_5/<str:batch_location>/', views.get_batches_5, name='Batches 5'),
    path('image/view/', views.get_images, name='View Images'),
    path('sensorLabel/', views.sensor_label, name='Create Sensor Labels'),
    path('s_labels/', views.labels, name='View Sensor Labels'),
    path('s_l/', views.labels_lst, name='Drop down list of labels'),
    path('verify_sensors/', views.verify_sensors, name='Verify Sensors'),
    path('assign_labels/', views.assign_labels, name='Assign Sensor Labels'),
    path('verify_sensors_2/', views.verify_sensors_2, name='Verify Sensors'),
    path('assign_labels_2/', views.assign_labels_2, name='Assign Sensor Labels'),
    path('assign_labels_3/', views.assign_labels_3, name='Assign Labels with Description included'),
    path('sensor/bulk-update/', views.update_sensors_labels_2, name='Update sensors in bulk'),
    path('verify_sensors_3/', views.verify_sensors_3, name='Verify Sensors')
]